{% set name = "xeus-cling" %}
{% set version = "0.5.1" %}
{% set sha256 = "79b970b1b154d61f173e33f626eff650a17b37b5eb4d550e89a7c8aff2e86c5a" %}

{% set clang_version = [5, 0, 0] %}
{% set cling_version = "0.5" %}
{% set clang_patches_version = "6.14.06" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xeus-cling/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # Cling has not been built for windows yet
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - cppzmq >=4.3.0,<4.4.0
    - zeromq >=4.3.1,<4.4.0
    - xeus >=0.19.1,<0.20
    - xtl >=0.6.1,<0.7
    - pugixml
    - cxxopts >=2.1.1,<3.0
    - nlohmann_json >=3.5.0,<4.0
    - dirent >=1.21,<2.0  # [win]
    - zlib
    - llvmdev {{ clang_version[0] }}
    - clangdev {{ clang_version|join('.') }}
    - clang_variant * cling_{{ clang_patches_version }}
    - cling {{ cling_version }}
  run:
    # Even though cppzmq, xtl and nlohmann_json are header-only,
    # they are used at runtime by the c++ interpreter.
    - {{ pin_compatible('cppzmq', max_pin='x.x') }}
    - {{ pin_compatible('xtl', max_pin='x.x') }}
    - {{ pin_compatible('nlohmann_json', max_pin='x.x') }}

test:
  commands:
    - test -f ${PREFIX}/bin/xcpp  # [unix]
    - if exist %LIBRARY_PREFIX%\bin\xcpp.exe (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xeus-cling
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Cling-based C++ kernel for Jupyter based on xeus'
  description: 'Jupyter kernel for the C++ programming language'
  doc_url: http://xeus-cling.readthedocs.io
  dev_url: https://github.com/QuantStack/xeus-cling

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
    - martinRenou
