{% set name = "xeus-cling" %}
{% set version = "0.15.2" %}
{% set sha256 = "f6a85ee64578656c8d3374253ad9f68bc74eaf317175c68cb169ff80972fb444" %}

{% set clang_version = [9, 0, 1] %}
{% set cling_version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jupyter-xeus/xeus-cling/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # Cling has not been built for windows yet
  skip: true  # [not linux or aarch64]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - cppzmq >=4.6.0,<5
    - xeus-zmq >=1.1.0,<2.0
    - xtl >=0.7,<0.8
    - pugixml
    - cpp-argparse >=2.9,<3
    - nlohmann_json >=3.9.1,<4
    - dirent >=1.21,<2.0  # [win]
    - zlib
    - llvmdev {{ clang_version[0] }}
    - clangdev {{ clang_version|join('.') }} cling_v{{ cling_version }}*
    - cling {{ cling_version }}
  run:
    # Even though cppzmq, xtl and nlohmann_json are header-only,
    # they are used at runtime by the c++ interpreter.
    - {{ pin_compatible('cppzmq', max_pin='x.x') }}
    - {{ pin_compatible('xtl', max_pin='x.x') }}
    - {{ pin_compatible('nlohmann_json', max_pin='x.x') }}

test:
  requires:
    - jupyter_kernel_test
  commands:
    - test -f ${PREFIX}/bin/xcpp  # [unix]
    - if exist %LIBRARY_PREFIX%\bin\xcpp.exe (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/jupyter-xeus/xeus-cling
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Cling-based C++ kernel for Jupyter based on xeus
  description: Jupyter kernel for the C++ programming language
  doc_url: https://xeus-cling.readthedocs.io
  dev_url: https://github.com/jupyter-xeus/xeus-cling

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
    - martinRenou
